# Generated by Django 6.0.5 on 2026-05-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_code', models.TextField()),
                ('task_description', models.TextField()),
                ('model_used', models.CharField(max_length=150)),
                ('assumptions', models.JSONField(default=dict)),
                ('simplicity_check', models.JSONField(default=dict)),
                ('modified_code', models.TextField()),
                ('verifiable_goals', models.JSONField(default=list)),
                ('raw_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
